language: node_js
node_js:
- '6'
- '7'
cache: yarn
script: npm run test
before_deploy:
- npm run build
deploy:
  provider: npm
  email: benjamin.otto@style-systems.de
  api_key:
    secure: TQd8xUdwuFk4hFxcsTVpyEZoGusYCP1KYTK1GLKBnNzmR2odcSoBZO2F/D3guaewG8KiJXvt6Qu9pAqnIvpHRFkoJMASzD0IwaMvr47KwFxLuRSnikK4sdO3pMceqJUy0zktyGDFieybv8t13SRIIIrQzKIYhuR6e+U1FbaPAuZZtcFZ7hxksrMENsJG/JGGFwCAJ+Gmezez7kOYl+NmQw+MzF8tFfqwMP5QVnku1k41po1GQ1IDNpG50QzI9bEprrqmwGzAVW3Up6cQp/L4U9ksYhBZTzCHYaggUD614lhUHIogMQOc6tmHJxIs/LbbIVs010/m+2IwUN5txPp2cWGSQ9M74R/82fg1qH8Gq5i0dbaf77bpX/KutH8bNX7gFQYqvA7mVfmQYrRT6yekaiYAb+qD3xFKp/lJU5CKZj1AqDVWmvMo+GaaBpkH8uPNIYO7CrwG4eYyckpJKigQEqS6y3e/FGnjt0fRvjG6ZM25GtU8xSd0AhbC1LCOr6LACerxHDDv71bHgKyZgYv3FvB6SDBRbvazw+hHaQKZ/mUzeYPQTEIWgjvBJOMGWXh7SqiIGz9aavraMKqO30toZYvSOfZxr+85oZT7dNKOjLqCJzOIIs2+IERlghLN1zzK4xaYULJ5GZssDDdAwsgCnspdmXd8T/z42p4nyWpIunY=
  on:
    tags: true
    repo: otbe/snapshot-dir
